jobs:
  include:
    - os: linux
      dist: focal
      name: "SBOM generation example job"
      language: ruby
      addons:
        sbom:
          on:
            all_branches: true
      script:
        - gem build ./ruby/hello_world.gemspec
        - pwd
        - ls -la /home/travis/build/piccadilly-circus/sbom-regression
        - ls -la /home/travis/build/
        - ls -la /home/travis/builds/
        - ls -la ~
      on_success:
        - echo "SBOM generation example job passed"
  
