jobs:
  include:
    - name: Linux Focal Ruby
      os: linux
      dist: focal
      language: ruby
      addons:
        sbom:
          on:
            branch: sbom-test
          run_phase: after_success
          output_format: cyclonedx-json
          input_dir: '/sbom/ruby'
          output_dir: '/sbom/ruby'
      script:
        - gem build ./ruby/hello_world.gemspec
        - pwd
        - ls -la /home/travis/build/
        - ls -la /home/travis/build/piccadilly-circus/sbom-regression
        - cat /home/travis/build/piccadilly-circus/sbom-regression/deployable_application-1.0.gem
        - ls -la /home/travis/build/
        - ls -la ~
  
