jobs:
  include:
    - name: Linux Focal Ruby
      os: linux
      dist: focal
      language: ruby
      addons:
        sbom:
          on:
            branch: main
          run_phase: after_success
          output_format: cyclonedx-json
      script:
        - gem build ./ruby/hello_world.gemspec
  
