jobs:
  include:
    - os: linux
      dist: focal
      name: "SBOM generation example job"
      language: ruby
      addons:
        sbom:
          on:
            all_branches: true
          input_dir: "sbom/ruby"
          output_dir: "sbom/ruby"
      script:
        - gem build ./ruby/hello_world.gemspec
        - pwd
        - ls -la /home/travis/build/piccadilly-circus/sbom-regression
        - ls -la /home/travis/build/
        - ls -la ~
  
